//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class tiendaEntities : DbContext
{
    public tiendaEntities()
        : base("name=tiendaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<base_cotizaciones_estatus> base_cotizaciones_estatus { get; set; }
    public DbSet<productos_comentarios> productos_comentarios { get; set; }
    public DbSet<productos_stock> productos_stock { get; set; }
    public DbSet<pedidos_pagos_paypal> pedidos_pagos_paypal { get; set; }
    public DbSet<glosario> glosario { get; set; }
    public DbSet<infografías> infografías { get; set; }
    public DbSet<carrito_productos> carrito_productos { get; set; }
    public DbSet<direcciones_envio> direcciones_envio { get; set; }
    public DbSet<direcciones_facturacion> direcciones_facturacion { get; set; }
    public DbSet<estados_mexico> estados_mexico { get; set; }
    public DbSet<pais> paises { get; set; }
    public DbSet<pedidos_direccionFacturacion> pedidos_direccionFacturacion { get; set; }
    public DbSet<pedidos_modificaciones> pedidos_modificaciones { get; set; }
    public DbSet<pedidos_productos> pedidos_productos { get; set; }
    public DbSet<pedidos_productos_modificaciones> pedidos_productos_modificaciones { get; set; }
    public DbSet<precios_ListaFija> precios_ListaFija { get; set; }
    public DbSet<precios_multiplicador> precios_multiplicador { get; set; }
    public DbSet<precios_rangos> precios_rangos { get; set; }
    public DbSet<productos_Roles> productos_Roles { get; set; }
    public DbSet<productos_unidades> productos_unidades { get; set; }
    public DbSet<permisos_app> permisos_app { get; set; }
    public DbSet<cotizaciones_datos> cotizaciones_datos { get; set; }
    public DbSet<cotizaciones_productos> cotizaciones_productos { get; set; }
    public DbSet<productos_Datos> productos_Datos { get; set; }
    public DbSet<pedidos_pagos_liga_santander> pedidos_pagos_liga_santander { get; set; }
    public DbSet<pedidos_pagos_respuesta_santander> pedidos_pagos_respuesta_santander { get; set; }
    public DbSet<cotizaciones_datosNumericos> cotizaciones_datosNumericos { get; set; }
    public DbSet<cotizaciones_direccionEnvio> cotizaciones_direccionEnvio { get; set; }
    public DbSet<pedidos_direccionEnvio> pedidos_direccionEnvio { get; set; }
    public DbSet<pedidos_datos> pedidos_datos { get; set; }
    public DbSet<pedidos_datosNumericos> pedidos_datosNumericos { get; set; }
    public DbSet<contacto> contactos { get; set; }
    public DbSet<usuarios_ligas_confirmaciones> usuarios_ligas_confirmaciones { get; set; }
    public DbSet<categoria> categorias { get; set; }
    public DbSet<usuario> usuarios { get; set; }
    public DbSet<pedidos_pagos_transferencia> pedidos_pagos_transferencia { get; set; }
    public DbSet<productos_solo_visualizacion> productos_solo_visualizacion { get; set; }
    public DbSet<precios_fantasma> precios_fantasma { get; set; }
    public DbSet<PedidosClaveUsoCFDI> PedidosClaveUsoCFDIs { get; set; }
    public DbSet<ProductosBloqueoStock> ProductosBloqueoStocks { get; set; }
    public DbSet<usuariosInfo> usuariosInfoes { get; set; }
}
