import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>INCOM test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-full h-screen flex justify-center items-center border border-red-500 bg-blue-50'>
        <p className='font-semibold text-xl'>Aplicación de NEXTJS</p>
      </main>
    </div>
  )
}
